console.log("BUILD THE REQUIRED FILES")
const fs = require('fs')
const darktheme = fs.readFileSync("./src/static/dark-theme.css", "utf8");
const writeData = `/*
THIS FILE IS AUTOMATICALLY GENERATED FILE
*/
export default \`
${darktheme}
\`\n`
fs.writeFileSync("./src/theme/dark.ts", writeData, "utf8");
const gettrackinfo = fs.readFileSync("./src/static/get-trackinfo.js", "utf8");
const writeData2 = `/*
THIS FILE IS AUTOMATICALLY GENERATED FILE
*/
/**
 * Retrieves information about the currently playing track on the page.
 * @returns {Promise<string>} A JSON string containing the title, author, artwork URL, and URL of the currently playing track.
 */
export const getTracks = \`
${gettrackinfo}
\`\n`
fs.writeFileSync("./src/lib/GetTrackInfo.ts", writeData2, "utf8");
console.log("COMPLETED BUILD OF REQUIRED FILES")